docs_list_title: services
docs:

- title: Training
  url: /training/
  icon: <i class="fas fa-certificate"></i>
  description: Get training to help your agency establish remote / telework policies and best practices.

- title: Coaching
  url: /coaching/
  icon: <i class="fas fa-shapes"></i>
  description: Get coaching to help your agency establish remote / telework policies and best practices.

- title: Consulting
  url: /consulting/
  icon: <i class="fas fa-lightbulb"></i>
  description: Get consulting to help your agency establish remote / telework policies and best practices.