docs_list_title: services
docs:

- title: Training
  url: /training/
  icon: <i class="fas fa-certificate"></i>
  description: Get customizable training for small or large groups at your agency on remote / telework best practices.
  excerpt: Get customizable training for small or large groups at your agency on remote / telework best practices.

- title: Coaching
  url: /coaching/
  icon: <i class="fas fa-shapes"></i>
  description: Get personalized coaching for individuals or small groups at your agency to master the skills needed for effective distributed teams.
  excerpt: Get personalized coaching for individuals or small groups at your agency to master the skills needed for effective distributed teams.

- title: Consulting
  url: /consulting/
  icon: <i class="fas fa-lightbulb"></i>
  description: Get one-on-one consulting for orientation on effective telework policies and best practices, along with personalized recommendations for your agency.
  excerpt: Get one-on-one consulting for orientation on effective telework policies and best practices, along with personalized recommendations for your agency.